AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  telegram-agentcore-bot
  
  AgentCore Processor for multi-channel message processing

Parameters:
  EventBusName:
    Type: String
    Description: EventBridge Event Bus Name (from telegram-lambda stack)
    Default: ''

  EventBusArn:
    Type: String
    Description: EventBridge Event Bus ARN (from telegram-lambda stack)
    Default: ''

  BedrockModelId:
    Type: String
    Description: Bedrock Model ID for AgentCore
    Default: 'anthropic.claude-3-5-sonnet-20241022-v2:0'

  BedrockAgentCoreMemoryId:
    Type: String
    Description: Optional Bedrock AgentCore Memory ID
    Default: ''

  ReceiverStackName:
    Type: String
    Description: Name of the telegram-lambda-receiver stack for importing S3 bucket
    Default: 'telegram-lambda-receiver'

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  # Agent Processor Lambda Function
  AgentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-processor'
      CodeUri: .
      Handler: processor_entry.handler
      Description: Process messages from EventBridge using AgentCore
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref EventBusName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          BEDROCK_AGENTCORE_MEMORY_ID: !Ref BedrockAgentCoreMemoryId
          BROWSER_ENABLED: 'true'
          FILE_ENABLED: 'true'
          FILE_STORAGE_BUCKET: !ImportValue 
            Fn::Sub: '${ReceiverStackName}-FileStorageBucket'
      Policies:
        - Statement:
            # EventBridge
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: '*'
            
            # Bedrock AI
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:InvokeAgent
                - bedrock:Retrieve
              Resource: '*'
            
            # Browser Sandbox
            - Effect: Allow
              Action:
                - bedrock-agentcore:StartBrowserSession
                - bedrock-agentcore:StopBrowserSession
                - bedrock-agentcore:GetBrowserSession
                - bedrock-agentcore-control:*
              Resource: '*'
            
            # Code Interpreter (File Processing)
            - Effect: Allow
              Action:
                - bedrock-agentcore:StartCodeInterpreterSession
                - bedrock-agentcore:StopCodeInterpreterSession
                - bedrock-agentcore:InvokeCodeInterpreter
              Resource: '*'
            
            # Memory
            - Effect: Allow
              Action:
                - bedrock-agentcore:ListEvents
                - bedrock-agentcore:GetEvent
                - bedrock-agentcore:PutEvent
                - bedrock-agentcore:CreateEvent
                - bedrock-agentcore:DeleteEvent
                - bedrock-agentcore:GetMemory
                - bedrock-agentcore:UpdateMemory
                - bedrock-agentcore:CreateMemory
                - bedrock-agentcore:ListMemories
                - bedrock-agentcore:ListSessions
                - bedrock-agentcore:GetSession
                - bedrock-agentcore:CreateSession
                - bedrock-agentcore:ListMemoryRecords
                - bedrock-agentcore:GetMemoryRecord
                - bedrock-agentcore:RetrieveMemoryRecords
              Resource: '*'
            
            # S3 File Storage (Read Only)
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub
                - '${BucketArn}/*'
                - BucketArn: !ImportValue 
                    Fn::Sub: '${ReceiverStackName}-FileStorageBucketArn'
      Tags:
        Service: telegram-agentcore-bot
        Component: processor
        auto-delete: "no"

  # CloudWatch Log Group
  ProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AgentProcessorFunction}'
      RetentionInDays: 14

  # EventBridge Permission for Lambda
  ProcessorEventBridgePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AgentProcessorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*'

Outputs:
  ProcessorFunctionArn:
    Description: Agent Processor Lambda ARN
    Value: !GetAtt AgentProcessorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProcessorArn'

  ProcessorFunctionName:
    Description: Agent Processor Lambda Function Name
    Value: !Ref AgentProcessorFunction
    Export:
      Name: !Sub '${AWS::StackName}-ProcessorName'

  ProcessorLogGroup:
    Description: CloudWatch Log Group for Processor
    Value: !Ref ProcessorLogGroup

  DeploymentInstructions:
    Description: Instructions for connecting to EventBridge
    Value: !Sub |
      After deploying this stack, update the telegram-lambda MessageReceivedRule with this target:
      aws events put-targets --rule ${EventBusName}-message-received --event-bus-name ${EventBusName} --targets "Id"="AgentProcessor","Arn"="${AgentProcessorFunction.Arn}"
